name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Run unit tests
      shell: bash
      run: npm run test 2>&1 | tee build_failure.log

    - name: AI Build Assistant
      if: failure()
      uses: saimjawed254/accenture-intern-assignment@main
      with:
        log-file: 'build_failure.log'
        gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
